// Default `flutter create` scaffold test replaced to target the real app.
// The counter-app template generated by the Flutter tooling references a
// non-existent `MyApp`, so we delegate coverage to `smoke_test.dart` and keep
// this file as a compile-check that the public entrypoint imports cleanly.

import 'package:book_club/app.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('BookClubApp type symbol is importable', () {
    expect(BookClubApp, isNotNull);
  });
}
